# -*- coding: utf-8 -*-
"""ML Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJ2SymK0dApTxrM4-w7kKdRkHtj8zsKt

**Dataset Check**
"""

import pandas as pd
df = pd.read_csv('bank-full.csv')

print("Total instances:", len(df))
print("Total columns:", len(df.columns))
print("\nage mean:", round(df['age'].mean(), 1), "| min:", df['age'].min(), "| max:", df['age'].max())
print("balance mean:", round(df['balance'].mean(), 1), "| min:", df['balance'].min(), "| max:", df['balance'].max())
print("day min:", df['day'].min(), "| max:", df['day'].max())
print("duration mean:", round(df['duration'].mean(), 1), "| max:", df['duration'].max())
print("campaign mean:", round(df['campaign'].mean(), 1))
print("previous mean:", round(df['previous'].mean(), 1))
print("\njob categories:", df['job'].nunique())
print("marital categories:", df['marital'].nunique())
print("education categories:", df['education'].nunique())
print("month categories:", df['month'].nunique())
print("\nClass counts:", df['y'].value_counts().to_dict())
print("Class %:", round(df['y'].value_counts(normalize=True)*100, 1).to_dict())
print("\nMissing values:", df.isnull().sum().sum())

df.head()

import pandas as pd

df = pd.read_csv('bank-full.csv')

print("Categorical Features:\n")
categorical = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']
for col in categorical:
    print(f"{col}: {df[col].nunique()} categories → {df[col].unique()}\n")

"""**Data Preprocessing**"""

import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv('bank-full.csv')

# CHECK MISSING VALUES
print(df.isnull().sum())

# CHECK CLASS DISTRIBUTION
print(df['y'].value_counts())

"""**BALANCING THE DATA**"""

# Separating the two classes
df_yes = df[df['y'] == 'yes']
df_no  = df[df['y'] == 'no']

print('Before balancing:')
print(df['y'].value_counts())

# Undersampling the majority class to match minority class size
df_no_sampled = df_no.sample(n=len(df_yes), random_state=42)

# Combining and shuffling the data
df = pd.concat([df_yes, df_no_sampled]).sample(frac=1, random_state=42).reset_index(drop=True)

print('\nAfter balancing:')
print(df['y'].value_counts())

"""**ORDINAL ENCODING**"""

from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, MinMaxScaler
# ORDINAL ENCODING
ord_enc = OrdinalEncoder()
df[['default', 'housing', 'loan']] = ord_enc.fit_transform(df[['default', 'housing', 'loan']])

# custom order for 'y' column
custom_order = [['no', 'yes']]

# Apply custom ordinal encoding to target variable
enc = OrdinalEncoder(categories=custom_order)
df[['y']] = enc.fit_transform(df[['y']])

# Display first 10 rows
df.head(10)

"""**ONE HOT ENCODING**"""

# Initialize OneHotEncoder
onehot_enc = OneHotEncoder()

# Apply one-hot encoding to each categorical column
for col in ['job', 'marital', 'education', 'contact', 'month', 'poutcome']:
    onehot_result = onehot_enc.fit_transform(df[[col]])
    new_df = pd.DataFrame(onehot_result.toarray(), columns=[col + '_' + c for c in onehot_enc.categories_[0]])

    # Join new cols and drop original
    df = df.join(new_df)
    df = df.drop(columns=[col])

print(df.head())
print("\n")
print(df.describe())
print("\nShape after encoding:", df.shape)

print("\nColumn Names: ")
for col in df.columns:
    print(col)

"""**Spliting data**"""

y = df['y'].to_numpy()
X = df.drop(columns=['y']).to_numpy()

# TRAIN TEST SPLIT
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# SCALING
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Preprocessing complete!")
print("Training set size:", X_train.shape)
print("Testing set size:", X_test.shape)

"""**Descision Tree Classifier**"""

from sklearn.tree import DecisionTreeClassifier
import numpy as np

# Test max_depth values
max_depth_values = [2, 4, 6, 8, 10, None]
max_depth_scores = []

# Loop through each depth value to evaluate performance
print("Testing max_depth values:")
for depth in max_depth_values:
    dt = DecisionTreeClassifier(max_depth=depth, random_state=42)
    dt.fit(X_train, y_train)
    score = dt.score(X_test, y_test)
    max_depth_scores.append(score)
    print(f"  max_depth={depth}: Accuracy = {score:.4f}")

# Find best performing max_depth
best_idx = np.argmax(max_depth_scores)
best_max_depth = max_depth_values[best_idx]
print(f"\nBest max_depth: {best_max_depth} (Accuracy: {max_depth_scores[best_idx]:.4f})")

# Test min_samples_split values
min_samples_split_values = [2, 5, 10, 20, 30, 40, 60, 80]
min_samples_split_scores = []

print("Testing min_samples_split values:")
for split in min_samples_split_values:
    dt = DecisionTreeClassifier(min_samples_split=split, random_state=42)
    dt.fit(X_train, y_train)
    score = dt.score(X_test, y_test)
    min_samples_split_scores.append(score)
    print(f"  min_samples_split={split}: Accuracy = {score:.4f}")

best_idx = np.argmax(min_samples_split_scores)
best_min_samples_split = min_samples_split_values[best_idx]
print(f"\nBest min_samples_split: {best_min_samples_split} (Accuracy: {min_samples_split_scores[best_idx]:.4f})")

# Test min_impurity_decrease values
min_impurity_values = [0.0, 0.001, 0.01, 0.1]
min_impurity_scores = []

print("Testing min_impurity_decrease values:")
for impurity in min_impurity_values:
    dt = DecisionTreeClassifier(min_impurity_decrease=impurity, random_state=42)
    dt.fit(X_train, y_train)
    score = dt.score(X_test, y_test)
    min_impurity_scores.append(score)
    print(f"  min_impurity_decrease={impurity}: Accuracy = {score:.4f}")

best_idx = np.argmax(min_impurity_scores)
best_min_impurity = min_impurity_values[best_idx]
print(f"\nBest min_impurity_decrease: {best_min_impurity} (Accuracy: {min_impurity_scores[best_idx]:.4f})")

# Test ccp_alpha values
ccp_alpha_values = [0.0, 0.001, 0.01, 0.1]
ccp_alpha_scores = []

print("Testing ccp_alpha values:")
for alpha in ccp_alpha_values:
    dt = DecisionTreeClassifier(ccp_alpha=alpha, random_state=42)
    dt.fit(X_train, y_train)
    score = dt.score(X_test, y_test)
    ccp_alpha_scores.append(score)
    print(f"  ccp_alpha={alpha}: Accuracy = {score:.4f}")

best_idx = np.argmax(ccp_alpha_scores)
best_ccp_alpha = ccp_alpha_values[best_idx]
print(f"\nBest ccp_alpha: {best_ccp_alpha} (Accuracy: {ccp_alpha_scores[best_idx]:.4f})")

from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

best_dt = DecisionTreeClassifier(
    max_depth=8,
    min_samples_split=20,
    min_impurity_decrease=0.001,
    ccp_alpha=0.001,
    random_state=42
)

best_dt.fit(X_train, y_train)

# Make predictions
y_pred_dt = best_dt.predict(X_test)
y_proba_dt = best_dt.predict_proba(X_test)[:, 1]

# Calculate metrics
acc_dt = accuracy_score(y_test, y_pred_dt)
prec_dt = precision_score(y_test, y_pred_dt)
rec_dt = recall_score(y_test, y_pred_dt)
f1_dt = f1_score(y_test, y_pred_dt)
auc_dt = roc_auc_score(y_test, y_proba_dt)
cm_dt = confusion_matrix(y_test, y_pred_dt)

print("Decision Tree Performance:")
print(f"  Accuracy:  {acc_dt:.4f}")
print(f"  Precision: {prec_dt:.4f}")
print(f"  Recall:    {rec_dt:.4f}")
print(f"  F1-Score:  {f1_dt:.4f}")
print(f"  AUC:       {auc_dt:.4f}")
print(f"\nConfusion Matrix:\n{cm_dt}")

# Store Decision Tree
dt_results = {
    'Model': 'Decision Tree (Optimized)',
    'Accuracy': acc_dt,
    'Precision': prec_dt,
    'Recall': rec_dt,
    'F1': f1_dt,
    'AUC': auc_dt
}

"""**Naive Bayes - Testing Gaussian, Multinomial, and Bernoulli variants**"""

from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

# Gaussian Naive Bayes
gnb = GaussianNB()
gnb.fit(X_train, y_train)
gnb_score = gnb.score(X_test, y_test)
print(f"Gaussian Naive Bayes:    Accuracy = {gnb_score:.4f}")

# Multinomial Naive Bayes
mnb = MultinomialNB()
mnb.fit(X_train, y_train)
mnb_score = mnb.score(X_test, y_test)
print(f"Multinomial Naive Bayes: Accuracy = {mnb_score:.4f}")

# Bernoulli Naive Bayes
bnb = BernoulliNB()
bnb.fit(X_train, y_train)
bnb_score = bnb.score(X_test, y_test)
print(f"Bernoulli Naive Bayes:   Accuracy = {bnb_score:.4f}")

# Best variant
scores = [gnb_score, mnb_score, bnb_score]
names = ['Gaussian', 'Multinomial', 'Bernoulli']
best_idx = scores.index(max(scores))
print(f"\nBest variant: {names[best_idx]} (Accuracy: {scores[best_idx]:.4f})")

best_nb = GaussianNB()
best_nb.fit(X_train, y_train)

# Make predictions
y_pred_nb = best_nb.predict(X_test)
y_proba_nb = best_nb.predict_proba(X_test)[:, 1]

# Calculate  metrics
acc_nb = accuracy_score(y_test, y_pred_nb)
prec_nb = precision_score(y_test, y_pred_nb)
rec_nb = recall_score(y_test, y_pred_nb)
f1_nb = f1_score(y_test, y_pred_nb)
auc_nb = roc_auc_score(y_test, y_proba_nb)
cm_nb = confusion_matrix(y_test, y_pred_nb)

print("Gaussian Naive Bayes Performance:")
print(f"  Accuracy:  {acc_nb:.4f}")
print(f"  Precision: {prec_nb:.4f}")
print(f"  Recall:    {rec_nb:.4f}")
print(f"  F1-Score:  {f1_nb:.4f}")
print(f"  AUC:       {auc_nb:.4f}")
print(f"\nConfusion Matrix:\n{cm_nb}")

# Store Naive Bayes results
nb_results = {
    'Model': 'Naive Bayes (Gaussian)',
    'Accuracy': acc_nb,
    'Precision': prec_nb,
    'Recall': rec_nb,
    'F1': f1_nb,
    'AUC': auc_nb
}

"""**Cross Validation (model reliability)**"""

from sklearn.model_selection import cross_val_score

# Decision Tree
cv_dt = cross_val_score(best_dt, X_train, y_train, cv=5, scoring='roc_auc')
print(f"Decision Tree 5-Fold CV AUC: {cv_dt.mean():.4f} (+/- {cv_dt.std():.4f})")

# Naive Bayes
cv_nb = cross_val_score(best_nb, X_train, y_train, cv=5, scoring='roc_auc')
print(f"Naive Bayes 5-Fold CV AUC: {cv_nb.mean():.4f} (+/- {cv_nb.std():.4f})")

"""**PCA for 90% variance**"""

from sklearn.decomposition import PCA

pca = PCA(n_components=0.9)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

print(f"Original features: {X_train.shape[1]}")
print(f"PCA components: {pca.n_components_}")
print(f"Variance explained: {pca.explained_variance_ratio_.sum():.4f}")
print(f"Features reduced by: {X_train.shape[1] - pca.n_components_} ({(1 - pca.n_components_/X_train.shape[1])*100:.1f}%)")

# Decision Tree on PCA data
best_dt_pca = DecisionTreeClassifier(
    max_depth=8,
    min_samples_split=20,
    min_impurity_decrease=0.001,
    ccp_alpha=0.001,
    random_state=42
)

# Train model on PCA transformed data
best_dt_pca.fit(X_train_pca, y_train)

# Pred class labels on test set
y_pred_dt_pca = best_dt_pca.predict(X_test_pca)

# Get prob est for + class
y_proba_dt_pca = best_dt_pca.predict_proba(X_test_pca)[:, 1]

acc_dt_pca = accuracy_score(y_test, y_pred_dt_pca)
auc_dt_pca = roc_auc_score(y_test, y_proba_dt_pca)
prec_dt_pca = precision_score(y_test, y_pred_dt_pca)
rec_dt_pca  = recall_score(y_test, y_pred_dt_pca)
f1_dt_pca   = f1_score(y_test, y_pred_dt_pca)

print(f"Decision Tree + PCA: Accuracy = {acc_dt_pca:.4f}, AUC = {auc_dt_pca:.4f}")

# Naive Bayes on PCA data
best_nb_pca = GaussianNB()
best_nb_pca.fit(X_train_pca, y_train)

# Pred class labels on test set
y_pred_nb_pca = best_nb_pca.predict(X_test_pca)

# Get prob est for + class
y_proba_nb_pca = best_nb_pca.predict_proba(X_test_pca)[:, 1]

acc_nb_pca = accuracy_score(y_test, y_pred_nb_pca)
auc_nb_pca = roc_auc_score(y_test, y_proba_nb_pca)

prec_nb_pca = precision_score(y_test, y_pred_nb_pca)
rec_nb_pca  = recall_score(y_test, y_pred_nb_pca)
f1_nb_pca   = f1_score(y_test, y_pred_nb_pca)

print(f"Naive Bayes + PCA: Accuracy = {acc_nb_pca:.4f}, AUC = {auc_nb_pca:.4f}")

"""**Logistic Regression - Hyperparameter Tuning**"""

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# Define parameter grid for Logistic Regression
param_grid_lr = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear']
}

# GridSearchCV
grid_lr = GridSearchCV(
    LogisticRegression(max_iter=1000, random_state=42),
    param_grid_lr,
    cv=5,
    scoring='roc_auc',
    n_jobs=-1,
    verbose=1
)

grid_lr.fit(X_train, y_train)

print("LR HYPERPARAMETER TUNING")
print(f"Best Parameters: {grid_lr.best_params_}")
print(f"Best CV AUC: {grid_lr.best_score_:.4f}")

results_df_lr = pd.DataFrame(grid_lr.cv_results_)
results_df_lr = results_df_lr[['param_C', 'param_penalty', 'param_solver', 'mean_test_score']]
results_df_lr = results_df_lr.sort_values('mean_test_score', ascending=False)
results_df_lr.columns = ['C', 'penalty', 'solver', 'CV_AUC']
results_df_lr['CV_AUC'] = results_df_lr['CV_AUC'].round(4)
results_df_lr = results_df_lr.reset_index(drop=True)

results_df_lr

best_lr = grid_lr.best_estimator_

# Predictions
y_pred_lr = best_lr.predict(X_test)
y_proba_lr = best_lr.predict_proba(X_test)[:, 1]

# Calculating metrics
acc_lr = accuracy_score(y_test, y_pred_lr)
prec_lr = precision_score(y_test, y_pred_lr)
rec_lr = recall_score(y_test, y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr)
auc_lr = roc_auc_score(y_test, y_proba_lr)
cm_lr = confusion_matrix(y_test, y_pred_lr)

print("Logistic Regression Performance:")
print(f"  Accuracy:  {acc_lr:.4f}")
print(f"  Precision: {prec_lr:.4f}")
print(f"  Recall:    {rec_lr:.4f}")
print(f"  F1-Score:  {f1_lr:.4f}")
print(f"  AUC:       {auc_lr:.4f}")
print(f"\nConfusion Matrix:\n{cm_lr}")

"""**LR Cross Validation**"""

cv_lr = cross_val_score(best_lr, X_train, y_train, cv=5, scoring='roc_auc')
print(f"Logistic Regression 5-Fold CV AUC: {cv_lr.mean():.4f} (+/- {cv_lr.std():.4f})")

lr_results = {
    'Model': f'Logistic Regression ({grid_lr.best_params_})',
    'Accuracy': acc_lr,
    'Precision': prec_lr,
    'Recall': rec_lr,
    'F1': f1_lr,
    'AUC': auc_lr
}

"""**LR PCA**"""

# Logistic Regression on PCA
best_lr_pca = LogisticRegression(
    C=grid_lr.best_params_['C'],
    penalty=grid_lr.best_params_['penalty'],
    solver='liblinear',
    max_iter=1000,
    random_state=42
)
best_lr_pca.fit(X_train_pca, y_train)

# Predict class labels on test set
y_pred_lr_pca = best_lr_pca.predict(X_test_pca)

# Get prob est for + class
y_proba_lr_pca = best_lr_pca.predict_proba(X_test_pca)[:, 1]

acc_lr_pca = accuracy_score(y_test, y_pred_lr_pca)
auc_lr_pca = roc_auc_score(y_test, y_proba_lr_pca)

prec_lr_pca = precision_score(y_test, y_pred_lr_pca)
rec_lr_pca  = recall_score(y_test, y_pred_lr_pca)
f1_lr_pca   = f1_score(y_test, y_pred_lr_pca)

print(f"Logistic Regression + PCA: Accuracy = {acc_lr_pca:.4f}, AUC = {auc_lr_pca:.4f}")

"""**Comparision of all the models**"""

compare_data = {
    'Model':     ['Decision Tree', 'Naive Bayes', 'Logistic Regression',
                  'DT + PCA', 'NB + PCA', 'LR + PCA'],
    'Accuracy':  [acc_dt,  acc_nb,  acc_lr,
                  acc_dt_pca, acc_nb_pca, acc_lr_pca],
    'Precision': [prec_dt, prec_nb, prec_lr,
                  prec_dt_pca, prec_nb_pca, prec_lr_pca],
    'Recall':    [rec_dt,  rec_nb,  rec_lr,
                  rec_dt_pca, rec_nb_pca, rec_lr_pca],
    'F1':        [f1_dt,   f1_nb,   f1_lr,
                  f1_dt_pca, f1_nb_pca, f1_lr_pca],
    'AUC':       [auc_dt,  auc_nb,  auc_lr,
                  auc_dt_pca, auc_nb_pca, auc_lr_pca],
}

summary_df = pd.DataFrame(compare_data)
summary_df

"""**Confusion Matrix**"""

import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Decision Tree
sns.heatmap(cm_dt, annot=True, fmt='d', cmap='Greens', cbar=False, ax=axes[0], annot_kws={"size": 14})
axes[0].set_title('Decision Tree Confusion Matrix', fontsize=16)
axes[0].set_xlabel('Predicted', fontsize=14)
axes[0].set_ylabel('Actual', fontsize=14)

# Logistic Regression
sns.heatmap(cm_lr, annot=True, fmt='d', cmap='Purples', cbar=False, ax=axes[1], annot_kws={"size": 14})
axes[1].set_title('Logistic Regression Confusion Matrix', fontsize=16)
axes[1].set_xlabel('Predicted', fontsize=14)
axes[1].set_ylabel('Actual', fontsize=14)

# Naive Bayes
sns.heatmap(cm_nb, annot=True, fmt='d', cmap='Oranges', cbar=False, ax=axes[2], annot_kws={"size": 14})
axes[2].set_title('Naive Bayes Confusion Matrix', fontsize=16)
axes[2].set_xlabel('Predicted', fontsize=14)
axes[2].set_ylabel('Actual', fontsize=14)

plt.tight_layout()
plt.show()

from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

# Calculate ROC curves
fpr_dt, tpr_dt, _ = roc_curve(y_test, y_proba_dt)
fpr_lr, tpr_lr, _ = roc_curve(y_test, y_proba_lr)
fpr_nb, tpr_nb, _ = roc_curve(y_test, y_proba_nb)

# Plot
plt.figure(figsize=(8, 6))

plt.plot(fpr_dt, tpr_dt, color='green', lw=2, label=f'Decision Tree (AUC = {auc_dt:.4f})')
plt.plot(fpr_lr, tpr_lr, color='purple', lw=2, label=f'Logistic Regression (AUC = {auc_lr:.4f})')
plt.plot(fpr_nb, tpr_nb, color='orange', lw=2, label=f'Naive Bayes (AUC = {auc_nb:.4f})')

plt.plot([0, 1], [0, 1], color='gray', lw=1, linestyle='--', label='Random Classifier')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curves - Model Comparison')
plt.legend(loc='lower right')
plt.grid(True, alpha=0.3)
plt.show()